### ISSUE TITLE
No issue, but don't understand how it works

### ISSUE THREAD

**Issue by Arjan-21** [tregota/waitandswitch#1]
Hi Henrik,

I don't understand how the app works and in what situation.
If I read the description "This will turn on the Subwoofer if the TV power usage remain high and also turn it off if it remains low"
I'd think that it check again the status after the delay. So if the power usage of the tv is above "20w" than and it stays above "20w"  than the condition should be true. If it goes under "20w" and the delay is running than it should be false. 

But when I'm testing its more like a regular delay. Like you can use with then cards.

Or I thinking different than it works or I'm doing something wrong.

**Comment by tregota** [comment]
Ah. Yes it can be. It is a bit of a hack to work around limitations in the API. If you have a flow that triggers on changes in watts and the condition is that it is above 20w (followed by the waitandswitch cards) then it would have stopped a delay if the flow triggered again during the delay with a wattage below 20. And it doesn't result in false when that happens. It kills the flow. Resulting in neither true nor false. 
So it doesn't verify the condition again efter the delay. It has to trigger again during the delay.
Hope that helps.

**Comment by Arjan-21** [comment]
Thanks for your answer.
I understand now how it works. The "hack" is really usefull!
