### ISSUE TITLE
Adv.flow "Then Delay Yes/No x secs" card returns error

### ISSUE THREAD

**Issue by PeterKawa** [tregota/waitandswitch#2]
Hi Henrik,
I was testing your app with Advanced flow, but it returned an error. I used a THEN card in the top row:
![Screenshot from 2022-11-17 23-26-38](https://user-images.githubusercontent.com/74005072/202573729-e0af6250-861b-4ca1-ac33-38bfa2bc937a.png)

Best,
Peter

**Comment by tregota** [comment]
Hi, that is how it stops flows from continuing when interrupted by an opposing delay or as in your case, the cancel. It's a bit hacky but the errors are normal. Hope that clears it up.
Edit: you need to have the flow continue passed the delay card. I realise now I should probably make an advanced example in the readme

**Comment by PeterKawa** [comment]
Ah I see, thx! So it just doesn't work with the testmode of Adv.flow. 
Thx for the quick response.

**Comment by tregota** [comment]
No problem. Thanks for giving my app a go. I added an advanced flow example to the readme. Hopefully it helps someone.
https://github.com/tregota/waitandswitch#readme
