### ISSUE TITLE
Any thoughts on expanding this into a "Wait until all conditions"

### ISSUE THREAD

**Issue by golightlygl** [tregota/waitandswitch#3]
Hi,

After a lot of playing around I see what you've achieved here and for your specific use it appears ideal.  Well done.  But the important success I can see is combining multiple triggres into one flow which can't be done with the existing Advanced Flow logic.

However, I wonder if you have considered expanding the scenarios (or using the base code to write another app) that waits until both conditions are true?

ie to perfrom a real "ALL" function from  Advanced Flow: wait (for a set period of time) until all the triggers are true.

![Screenshot 2023-02-08 173010](https://user-images.githubusercontent.com/26927234/217607323-104d1aad-1c16-476f-aa2b-4985824f28df.jpg)

This would simplify so much and reduce half my advanced flows to about 50% of their size.

**Comment by tregota** [comment]
Hmm. it is an interesting idea. Sadly an app gets no information about the flow in which it is used. So the card has no way of knowing that there are two triggers connecting to it. That is why I'm resorting to using IDs.
So it probably would have to be done using a delay-card for each trigger, each with its own id. and then a separate card that checks if multiple IDs are all true.
Which would not be as tidy as your example.
